export const GET_RECENT_FILES_REQUEST = 'GET_RECENT_FILES_REQUEST';
export const GET_RECENT_FILES_SUCCESS = 'GET_RECENT_FILES_SUCCESS';
export const GET_RECENT_FILES_FAIL = 'GET_RECENT_FILES_FAIL';

export const GET_FILE_REQUEST = 'GET_FILE_REQUEST';
export const GET_FILE_SUCCESS = 'GET_FILE_SUCCESS';
export const GET_FILE_FAIL = 'GET_FILE_FAIL';

export const CREATE_FILE_REQUEST = 'CREATE_FILE_REQUEST';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAIL = 'CREATE_FILE_FAIL';
export const CREATE_FILE_RESET = 'CREATE_FILE_RESET';

export const UPDATE_FILE_REQUEST = 'UPDATE_FILE_REQUEST';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_FAIL = 'UPDATE_FILE_FAIL';
export const UPDATE_FILE_RESET = 'UPDATE_FILE_RESET';

export const UPDATE_FILE_FIELD_REQUEST = 'UPDATE_FILE_FIELD_REQUEST';
export const UPDATE_FILE_FIELD_SUCCESS = 'UPDATE_FILE_FIELD_SUCCESS';
export const UPDATE_FILE_FIELD_FAIL = 'UPDATE_FILE_FIELD_FAIL';
export const UPDATE_FILE_FIELD_RESET = 'UPDATE_FILE_FIELD_RESET';

export const UPDATE_FILENAME_REQUEST = 'UPDATE_FILENAME_REQUEST';
export const UPDATE_FILENAME_SUCCESS = 'UPDATE_FILENAME_SUCCESS';
export const UPDATE_FILENAME_FAIL = 'UPDATE_FILENAME_FAIL';
export const UPDATE_FILENAME_RESET = 'UPDATE_FILENAME_RESET';

export const DELETE_FILE_FIELD_REQUEST = 'DELETE_FILE_FIELD_REQUEST';
export const DELETE_FILE_FIELD_SUCCESS = 'DELETE_FILE_FIELD_SUCCESS';
export const DELETE_FILE_FIELD_FAIL = 'DELETE_FILE_FIELD_FAIL';
export const DELETE_FILE_FIELD_RESET = 'DELETE_FILE_FIELD_RESET';

export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL';
export const DELETE_FILE_RESET = 'DELETE_FILE_RESET';
