export const USER_CHECK_REQUEST = 'USER_CHECK_REQUEST';
export const USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS';
export const USER_CHECK_FAIL = 'USER_CHECK_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
